# Generated by Django 3.2.8 on 2021-12-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab3_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='picture',
            field=models.ImageField(upload_to='images/', verbose_name='images'),
        ),
    ]
