# Generated by Django 3.2.8 on 2021-12-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab3_web', '0002_alter_articles_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=20, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('password', models.CharField(max_length=20, verbose_name='Password')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flowerid', models.CharField(max_length=50, verbose_name='FlowerId')),
                ('email', models.CharField(max_length=20, verbose_name='Email')),
            ],
        ),
    ]
